name: "Release devcontainer features"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'features/src/**'
      - '!features/src/ruby/**'

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Temporarily move Ruby feature
        run: |
          mkdir -p /tmp/ruby-feature-backup
          mv features/src/ruby /tmp/ruby-feature-backup/

      - name: "Publish"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          generate-docs: "true"
          base-path-to-features: "./features/src"
          features-namespace: "rails/devcontainer/features"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore Ruby feature
        if: always()
        run: |
          mv /tmp/ruby-feature-backup/ruby features/src/
